# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new pod to Amazon EKS, when there is a push to the "prod" branch.

name: Deploy to EKS

on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'apps/link-cable/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: images
  EKS_DEPLOYMENT_NAME: swash-be
  EKS_CLUSTER: swash-cluster

permissions:
  contents: read

jobs:
  configure:
    name: Configure, Build, Upload, Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create image tag
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            # Extract the tag name by removing the "refs/tags/" prefix
            TAG_NAME="${{ github.ref_name }}"
            echo "IMAGE_TAG=$TAG_NAME-$SHA_SHORT" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=UNTAGGED-$SHA_SHORT" >> $GITHUB_ENV
          fi

      - name: Build and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to EKS.
          export IMAGE_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # Check if the image already exists in the ECR repository
          IMAGE_EXISTS=$(aws ecr describe-images --repository-name $ECR_REPOSITORY --image-ids imageTag=$IMAGE_TAG --region $AWS_REGION --output text || true)

          if [[ -z "$IMAGE_EXISTS" ]]; then
            docker compose build
            docker push $IMAGE_NAME
          fi
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Install and configure kubectl
        run: |
          curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-01-04/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Deploy to EKS
        run: |
          if kubectl get deployments swash-be; then
            kubectl set image deployment/$EKS_DEPLOYMENT_NAME images=${{steps.build-image.outputs.image_name}}
          else
            kubectl create deployment swash-be --image=${{steps.build-image.outputs.image_name}}
          fi
